-- Generated by Mocodo 4.3.2

CREATE TABLE Article (
  PRIMARY KEY (idArticle),
  idArticle           SERIAL NOT NULL,
  titre               VARCHAR(300),
  contenu             TEXT,
  noteArticle         SMALLINT,
  caracteristiques    VARCHAR(300),
  dateCreationArticle DATE,
  dateModification    DATE,
  idJeu               SERIAL NOT NULL,
  idImage             SERIAL NOT NULL,
  login               VARCHAR(300) NOT NULL,
  UNIQUE (idJeu),
  UNIQUE (idImage)
);

CREATE TABLE Avis (
  PRIMARY KEY (idJeu, titre),
  idJeu            SERIAL NOT NULL,
  titre            VARCHAR(300) NOT NULL,
  texte            TEXT,
  noteAvis         TINYINT,
  dateCreationAvis DATE,
  login            VARCHAR(300) NOT NULL
);

CREATE TABLE Categorie (
  PRIMARY KEY (idCategorie),
  idCategorie  SERIAL NOT NULL,
  nomCategorie VARCHAR(100)
);

CREATE TABLE CategoriesJeu (
  PRIMARY KEY (idJeu, idCategorie),
  idJeu       SERIAL NOT NULL,
  idCategorie SERIAL NOT NULL
);

CREATE TABLE Image (
  PRIMARY KEY (idImage),
  idImage   SERIAL NOT NULL,
  lienImage VARCHAR(300),
  idArticle SERIAL NULL
);

CREATE TABLE Jeu (
  PRIMARY KEY (idJeu),
  idJeu      SERIAL NOT NULL,
  nom        VARCHAR(300),
  prix       FLOAT,
  dateSortie DATE,
  synopsis   VARCHAR(1000)
);

CREATE TABLE Support (
  PRIMARY KEY (idSupport),
  idSupport  SERIAL NOT NULL,
  nomSupport VARCHAR(100)
);

CREATE TABLE SupportsJeu (
  PRIMARY KEY (idJeu, idSupport),
  idJeu     SERIAL NOT NULL,
  idSupport SERIAL NOT NULL
);

CREATE TABLE Utilisateur (
  PRIMARY KEY (login),
  login         VARCHAR(300) NOT NULL,
  mdp           VARCHAR(100),
  nom           VARCHAR(300),
  prenom        VARCHAR(300),
  mel           VARCHAR(300),
  dateNaissance DATE,
  modo          BOOLEAN,
  idImage       SERIAL NULL,
  UNIQUE (idImage)
);

ALTER TABLE Article ADD FOREIGN KEY (login) REFERENCES Utilisateur (login);
ALTER TABLE Article ADD FOREIGN KEY (idImage) REFERENCES Image (idImage);
ALTER TABLE Article ADD FOREIGN KEY (idJeu) REFERENCES Jeu (idJeu);

ALTER TABLE Avis ADD FOREIGN KEY (login) REFERENCES Utilisateur (login);
ALTER TABLE Avis ADD FOREIGN KEY (idJeu) REFERENCES Jeu (idJeu);

ALTER TABLE CategoriesJeu ADD FOREIGN KEY (idCategorie) REFERENCES Categorie (idCategorie);
ALTER TABLE CategoriesJeu ADD FOREIGN KEY (idJeu) REFERENCES Jeu (idJeu);

ALTER TABLE Image ADD FOREIGN KEY (idArticle) REFERENCES Article (idArticle);

ALTER TABLE SupportsJeu ADD FOREIGN KEY (idSupport) REFERENCES Support (idSupport);
ALTER TABLE SupportsJeu ADD FOREIGN KEY (idJeu) REFERENCES Jeu (idJeu);

ALTER TABLE Utilisateur ADD FOREIGN KEY (idImage) REFERENCES Image (idImage);
